[project]
name = "py-tlgbotcore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "telethon>=1.41.2",
    "requests>=2.32.0",
    "icecream>=2.1.3",
]

[project.scripts]
tlgbotcore = "bot.start_tlgbotcore:main"
